"""post model update

Revision ID: a65df6db8233
Revises: 0f4ee4aad755
Create Date: 2020-09-12 01:46:31.689386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65df6db8233'
down_revision = '0f4ee4aad755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'adults',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'total_members',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'total_members',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'adults',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
